version: '2'
services:
  api:
    image: agonciarz/json-server
    ports:
      - "3000:3000"
  tests:
    image: agonciarz/mvn-api-tests:latest
    environment:
      - API_ENDPOINT=http://api
      - API_PORT=3000
    volumes:
      - ./reports:/reports