version: '2'
services:
  api:
    image: agonciarz/json-server
    ports:
      - "3000:3000"
  tests:
    image: agonciarz/mvn-api-tests:latest
    environment:
      - BASE_URI=http://api:3000
    volumes:
      - ./reports:/reports